# Generated by Django 5.0.6 on 2026-08-04 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('length_ft', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width_ft', models.DecimalField(decimal_places=2, max_digits=6)),
                ('interior_style', models.CharField(max_length=100)),
                ('color_palette', models.CharField(blank=True, max_length=255)),
                ('user_prompt', models.TextField(blank=True, help_text="The user's free-text room description, as typed")),
                ('raw_prompt', models.TextField(help_text='Full engineered instruction sent to the LLM provider')),
                ('enhanced_prompt', models.TextField(blank=True, help_text="The LLM's professionally rewritten version of the user's prompt")),
                ('summary', models.TextField()),
                ('room_json', models.JSONField(help_text='Schema-validated scene used by the existing A-Frame RoomViewer3D')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='No longer collected from the user -- estimated by the LLM from budget_breakdown', max_digits=12, null=True)),
                ('budget_breakdown', models.JSONField(blank=True, default=dict)),
                ('maintenance_tips', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='Optional AI-generated hero image', null=True)),
                ('llm_provider_used', models.CharField(blank=True, max_length=30)),
                ('image_provider_used', models.CharField(blank=True, max_length=30)),
                ('is_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generated', 'Generated a design'), ('saved', 'Saved a design'), ('regenerated', 'Regenerated a design'), ('deleted', 'Deleted a design'), ('downloaded_pdf', 'Downloaded PDF')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='designs.design')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_json', models.JSONField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='designs.design')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='designs.design')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
